# Adam Flott <adam@npjh.com> Bash config

# Bash is awful, but required for this planet.

# All portable shell functions, aliases, etc should go here. This file
# is Bash specific
source $ROOT/.shells/portable.rc
